### ISSUE TITLE
LaTeX representation of PEPA models

### ISSUE THREAD

**Issue by sshephard2** [sshephard2/msc-project#1]
Some long system equations need to be reformatted properly to display in LaTeX in the report

**Comment by sshephard2** [comment]
Will need to manually modify the PEPA auto-generated LaTeX

**Comment by MattForshaw** [comment]
Hi Stephen,

Could you point me towards an example of an incorrectly typeset long equation? (PDF and source). I might be able to suggest a work-around without modifying the generated LaTeX each time.

Best wishes,
Matt

**Comment by sshephard2** [comment]
Thanks Matt - an example is the Distributed database with replication PEPA model in `models-components.tex` (the PDF is `Performance modelling of skewed demand in complex systems.pdf`)

The generated LaTeX uses an array and the system equation is in a `\multicolumn` section.  I expect it's a similar thing to tables where the default column width isn't specified in terms of pagewidth?
